VARIABLE_LABELS_UNITS = {
    "538": {"label": "Device Language", "unit": "unitless"},
    "584": {"label": "Ventilation Mode", "unit": "unitless"},
    "635": {"label": "Inspired O2 (FiO2)", "unit": "%"},
    "801": {"label": "Generic Device Status", "unit": "unitless"},
    "802": {"label": "Generic Device Status 2", "unit": "unitless"},
    "803": {"label": "Generic Device Status 3", "unit": "unitless"},
    "804": {"label": "Generic Device Status 4", "unit": "unitless"},
    "808": {"label": "Preoxygenation Status", "unit": "unitless"},
    "809": {"label": "Postoxygenation Status", "unit": "unitless"},
    "955": {"label": "Battery Running Alarm", "unit": "unitless"},
    "1188": {"label": "Low Expired Tidal Volume Alarm", "unit": "unitless"},
    "1190": {"label": "I:E Ratio", "unit": "unitless"},
    "1310": {"label": "Compliance", "unit": "mL/cmH2O"},
    "1314": {"label": "Spontaneous Respiration Rate", "unit": "1/min"},
    "1318": {"label": "Static Compliance", "unit": "mL/cmH2O"},
    "1319": {"label": "Static Resistance", "unit": "cmH2O/L/s"},
    "1320": {"label": "Mandatory Respiration Rate Setting", "unit": "1/min"},
    "1321": {"label": "Tidal Volume Setting", "unit": "mL"},
    "1347": {"label": "Inspiratory Time", "unit": "s"},
    "1348": {"label": "Expiratory Time", "unit": "s"},
    "1360": {"label": "Nebulizer Activation Status", "unit": "unitless"},
    "1361": {"label": "O2 Suction Status", "unit": "unitless"},
    "1370": {"label": "Battery Low Alarm", "unit": "unitless"},
    "1381": {"label": "Inspiratory Flow Setting", "unit": "L/min"},
    "1383": {"label": "Inspiratory Flow Trigger Setting", "unit": "L/min"},
    "1408": {"label": "Inspiratory Rise Time Setting", "unit": "s"},
    "1410": {"label": "Patient Category (Ventilator)", "unit": "unitless"},
    "1414": {"label": "Peak Airway Pressure", "unit": "cmH2O"},
    "1415": {"label": "Mean Airway Pressure", "unit": "cmH2O"},
    "1569": {"label": "Minimum Airway Pressure", "unit": "cmH2O"},
    "1657": {"label": "Expiratory Trigger LevelSetting", "unit": "%"},
    "1761": {"label": "Airway Resistance", "unit": "cmH2O/L/s"},
    "1763": {"label": "Static Plateau AirwayPressure", "unit": "cmH2O"},
    "1816": {"label": "Air Pressure Sensor Alarm", "unit": "unitless"},
    "1817": {"label": "O2 Pressure Sensor Alarm", "unit": "unitless"},
    "1889": {"label": "Device Standby Status", "unit": "unitless"},
    "1913": {"label": "Device Serial Number", "unit": "unitless"},
    "1959": {"label": "Patient Breathing Status", "unit": "unitless"},
    "2092": {"label": "Inspired Minute Volume", "unit": "L"},
    "2102": {"label": "Inspiratory Time Setting", "unit": "s"},
    "2104": {"label": "Positive End ExpiratoryPressure (PEEP) Setting", "unit": "cmH2O"},
    "2117": {"label": "High Airway Pressure Alarm", "unit": "unitless"},
    "2119": {"label": "Generic Gas Supply Alarm", "unit": "unitless"},
    "2122": {"label": "Device Hardware Error", "unit": "unitless"},
    "2132": {"label": "AC Power Supply FailureAlarm", "unit": "unitless"},
    "2255": {"label": "Device Date/Time", "unit": "unitless"},
    "2324": {"label": "Inspired Tidal Volume", "unit": "mL"},
    "2325": {"label": "Expired Tidal Volume", "unit": "mL"},
    "2326": {"label": "Expired Minute Volume", "unit": "L/min"},
    "2432": {"label": "Expired Spontaneous TidalVolume", "unit": "mL"},
    "2434": {"label": "Spontaneous Expired MinuteVolume", "unit": "L"},
    "2446": {"label": "Apnea Activation Status", "unit": "unitless"},
    "2546": {"label": "Low Expired Minute VolumeAlarm", "unit": "unitless"},
    "2583": {"label": "I:E Ratio Setting", "unit": "unitless"},
    "2759": {"label": "Support Pressure Setting", "unit": "cmH2O"},
    "2782": {"label": "Inspired O2 (FiO2) Setting", "unit": "%"},
    "2879": {"label": "Device Software Revision", "unit": "unitless"},
    "2968": {"label": "Plateau Airway Pressure", "unit": "cmH2O"},
    "2973": {"label": "Patient Disconnected Alarm", "unit": "unitless"},
    "2987": {"label": "Inspired Pressure Setting", "unit": "cmH2O"},
    "2994": {"label": "Device Alarm Audio Volume", "unit": "unitless"},
    "2996": {"label": "Drive Gas Type", "unit": "unitless"},
    "3907": {"label": "Control Breath Status", "unit": "unitless"},
    "3981": {"label": "Battery Remaining Time", "unit": "min"},
    "4289": {"label": "Battery Charge Alarm", "unit": "unitless"},
    "4390": {"label": "Device Alarm Silence Status", "unit": "unitless"},
    "4987": {"label": "Apnea Ventilation Delay", "unit": "s"},
    "4992": {"label": "Maximum Inspired Pressure Setting", "unit": "cmH2O"},
    "5029": {"label": "Pressure Ramp Setting (ASB Ramp)", "unit": "s"},
    "5374": {"label": "Expiratory Time Constant (RCexp)", "unit": "s"},
    "5647": {"label": "Ventilation Bias Flow Setting", "unit": "L/min"},
    "5945": {"label": "Total Respiration Rate", "unit": "1/min"},
    "5972": {"label": "Next Ventilation Action Delay Setting", "unit": "s"},
    "6287": {"label": "Patient Circuit Leak Alarm", "unit": "unitless"},
    "6388": {"label": "Endotracheal Tube Type", "unit": "unitless"},
    "6501": {"label": "O2 Replacement Alarm", "unit": "unitless"},
    "6507": {"label": "Device Display Failure", "unit": "unitless"},
    "7540": {"label": "Circuit Leak Rate (Auto Mode)", "unit": "mL/min"},
    "7629": {"label": "O2 Sensor Disconnected Alarm", "unit": "unitless"},
    "7914": {"label": "Device Model", "unit": "unitless"},
    "7974": {"label": "Low Airway Pressure Alarm", "unit": "unitless"},
    "8024": {"label": "Circuit O2 Alarm", "unit": "unitless"},
    "8304": {"label": "Front Panel Button Error", "unit": "unitless"},
    "8382": {"label": "Peak Inspiratory Pressure Setting", "unit": "cmH2O"},
    "8546": {"label": "Device Displayed Unit Codeof Flow", "unit": "unitless"},
    "8556": {"label": "Airway PressureMeasurement Source", "unit": "unitless"},
    "8557": {"label": "Flow Measurement Source", "unit": "unitless"},
    "8558": {"label": "O2 Measurement Source", "unit": "unitless"},
    "8559": {"label": "Patient Circuit Leak AlarmLimit", "unit": "%"},
    "8562": {"label": "End Flow Setting", "unit": "%"},
    "8577": {"label": "Sub-Atmospheric Paw Alarm", "unit": "unitless"},
    "8578": {"label": "Pmax Reached Alarm", "unit": "unitless"},
    "8579": {"label": "Plimit Reached Alarm", "unit": "unitless"},
    "8580": {"label": "PIP Not Achieved Alarm", "unit": "unitless"},
    "8582": {"label": "Circuit Occlusion Alarm", "unit": "unitless"},
    "8584": {"label": "Inspiration Stopped Alarm", "unit": "unitless"},
    "8591": {"label": "Volume Apnea Alarm", "unit": "unitless"},
    "8596": {"label": "Low FiO2 Alarm", "unit": "unitless"},
    "8597": {"label": "High FiO2 Alarm", "unit": "unitless"},
    "8598": {"label": "Low Respiration Rate Alarm", "unit": "unitless"},
    "8599": {"label": "High Respiration Rate Alarm", "unit": "unitless"},
    "8606": {"label": "Battery Failure Alarm", "unit": "unitless"},
    "8611": {"label": "Fan Failure", "unit": "unitless"},
    "8612": {"label": "Heater Failure", "unit": "unitless"},
    "9277": {"label": "Circuit Compliance LevelSetting", "unit": "mL/cmH2O"},
    "9278": {"label": "ASB End of Flow Setting", "unit": "%"},
    "9285": {"label": "Inspiratory Flow Due toNebulizer", "unit": "L/min"},
    "9584": {"label": "High Expired Minute VolumeAlarm", "unit": "unitless"},
    "9998": {"label": "Watchdog Present", "unit": "unitless"},
    "50021": {"label": "Device Alarm InactivationState", "unit": "unitless"},
    "52911": {"label": "Airway Flow Waveform", "unit": "L/min"},
    "52912": {"label": "Airway Volume Waveform", "unit": "mL"},
    "52913": {"label": "Airway Pressure Waveform", "unit": "cmH2O"},
    "52921": {"label": "Airway CO2 ConcentrationWaveform", "unit": "%"},
    "52922": {"label": "Airway O2 ConcentrationWaveform", "unit": "%"},
    "54013": {"label": "Ventilation Mode", "unit": "unitless"},
    "54021": {"label": "Ventilation Mode Primary", "unit": "unitless"},
    "54022": {"label": "Ventilation Mode Options", "unit": "unitless"},
    "1131201": {"label": "High Circuit O2 Alarm", "unit": "unitless"},
    # ...existing code...
    "6992":    {"label": "High Airway Pressure Alarm", "unit": "unitless"},
    "9891":    {"label": "Low Airway Pressure Alarm", "unit": "unitless"},
    "32210":   {"label": "Apnea Alarm", "unit": "unitless"},
    "32220":   {"label": "High Tidal Volume Alarm", "unit": "mL"},
    "72210":   {"label": "Low Tidal Volume Alarm", "unit": "mL"},
    "72220":   {"label": "High Minute Volume Alarm", "unit": "L/min"},
    "92611":   {"label": "Low Minute Volume Alarm", "unit": "L/min"},
    "92612":   {"label": "High Respiratory Rate Alarm", "unit": "breaths/min"},
    "1131202": {"label": "Low Respiratory Rate Alarm", "unit": "breaths/min"},
    "1131206": {"label": "Oxygen Concentration High Alarm", "unit": "%"},
    "1131207": {"label": "Oxygen Concentration Low Alarm", "unit": "%"}

    "1425":   {"label": "Delta Esophageal Pressure", "unit": "mbar"},
    "3425":   {"label": "Ambient Atmospheric Pressure", "unit": "mbar"},
    "3668":   {"label": "Generic Delta Pressure", "unit": "mbar"},
    "7498":   {"label": "Inspiratory Transpulmonary Pressure", "unit": "cmH2O"},
    "7519":   {"label": "Expiratory Transpulmonary Pressure", "unit": "cmH2O"},
    "52341":  {"label": "P0.1 Occlusion Pressure", "unit": "cmH2O"},

    "9145":   {"label": "RSBI", "unit": "unitless"},
    "52112":  {"label": "Mandatory Respiration Rate", "unit": "1/min"},

    "6986":   {"label": "SBT Respiration Rate", "unit": "1/min"},
    "9123":   {"label": "SBT Duration Setting", "unit": "min"},

    "52252":  {"label": "Airway Dead Space", "unit": "mL"},
    "52253":  {"label": "Alveolar Tidal Ventilation", "unit": "mL"},
    "52254":  {"label": "Lung Trapped Volume", "unit": "mL"},

    "1398":   {"label": "Minute Volume Setting", "unit": "mL/kg/min"},
    "5359":   {"label": "Airway Peak Flow Setting", "unit": "L/min"},
    "7669":   {"label": "Tidal Volume Indexed By Body Weight Setting", "unit": "mL/kg"},
    "9288":   {"label": "Tidal Volume Indexed By Body Weight", "unit": "mL/kg"},
    "52211":  {"label": "Expired Tidal Volume", "unit": "mL"},
    "52323":  {"label": "Intrinsic PEEP (PEEPi)", "unit": "cmH2O"},
    "54072":  {"label": "Ventilator Work of Breathing", "unit": "J/L"},
    "1131102": {"label": "Extent Compensation Resistance Setting", "unit": "%"},
    "1131103": {"label": "Extent Compensation Compliance Setting", "unit": "%"},

    "7937":   {"label": "Cuff Inflation Pressure", "unit": "mbar"},

    "51052":  {"label": "SpO2 Pulse Rate", "unit": "1/min"},
    "51107":  {"label": "SpO2", "unit": "%"},

    "52515":  {"label": "End Tidal CO2 Partial Pressure", "unit": "mmHg"},
    "52517":  {"label": "Inspired CO2 Partial Pressure", "unit": "mmHg"},
    "52865":  {"label": "CO2 Minute Production", "unit": "mL/min"},
    # Generic Alarm variables
    "286":   {"label": "Generic Alarm 2", "unit": "unitless"},
    "294":   {"label": "Generic Alarm 10", "unit": "unitless"},
    "295":   {"label": "Generic Alarm 11", "unit": "unitless"},
    "296":   {"label": "Generic Alarm 12", "unit": "unitless"},
    "297":   {"label": "Generic Alarm 13", "unit": "unitless"},
    "298":   {"label": "Generic Alarm 14", "unit": "unitless"},
    # Battery alarm variable
    "2120": {"label": "Battery alarm", "unit": "unitless"},
    # Pressure alarms
    "3258": {"label": "Pressure alarm", "unit": "unitless"},
    "3717": {"label": "Pressure alarm", "unit": "unitless"},
    "72312": {"label": "Pressure alarm", "unit": "unitless"},
    "72313": {"label": "Pressure alarm", "unit": "unitless"},
    "1131203": {"label": "Pressure alarm", "unit": "unitless"},
    "1131208": {"label": "Pressure alarm", "unit": "unitless"},
    # Respiration alarms
    "8023": {"label": "Respiration alarm", "unit": "unitless"},
    "31060": {"label": "Respiration alarm", "unit": "unitless"},
    "71063": {"label": "Respiration alarm", "unit": "unitless"},
    "72111": {"label": "Respiration alarm", "unit": "unitless"},
    # NIBP alarms
    "1131204": {"label": "NIBP alarm", "unit": "unitless"},
    "1131205": {"label": "NIBP alarm", "unit": "unitless"},
# ...existing code...
# ...existing code...
    # --- Added from Variable Availability in index.html ---
    "1649": {"label": "Device variable", "unit": "unitless"},
    "2553": {"label": "Device variable", "unit": "unitless"},
    "4164": {"label": "Minimum Airway Pressure Setting", "unit": "unitless"},
    "5005": {"label": "Device variable", "unit": "unitless"},
    "570": {"label": "Device variable", "unit": "unitless"},
    "571": {"label": "Device variable", "unit": "unitless"},
    "572": {"label": "Device variable", "unit": "unitless"},
    "573": {"label": "Device variable", "unit": "unitless"},
    "574": {"label": "Device variable", "unit": "unitless"},
    "575": {"label": "Device variable", "unit": "unitless"},
    "9150": {"label": "Device variable", "unit": "unitless"},
    "52254": {"label": "Airway variable", "unit": "unitless"},
    "52341": {"label": "Pressure variable", "unit": "unitless"},
    "6389": {"label": "Device variable", "unit": "unitless"},
    "7937": {"label": "NIBP variable", "unit": "unitless"},
    "51052": {"label": "SpO2 variable", "unit": "unitless"},
    "51107": {"label": "SpO2 variable", "unit": "unitless"},
    "52112": {"label": "Respiration variable", "unit": "unitless"},
    "52252": {"label": "Airway variable", "unit": "unitless"},
    "52253": {"label": "Airway variable", "unit": "unitless"},
    "52865": {"label": "CO2 variable", "unit": "unitless"},
    "286": {"label": "Generic alarm variable", "unit": "unitless"},
    "294": {"label": "Generic alarm variable", "unit": "unitless"},
    "295": {"label": "Generic alarm variable", "unit": "unitless"},
    "296": {"label": "Generic alarm variable", "unit": "unitless"},
    "297": {"label": "Generic alarm variable", "unit": "unitless"},
    "298": {"label": "Generic alarm variable", "unit": "unitless"},
    "1425": {"label": "Pressure variable", "unit": "unitless"},
    "3258": {"label": "Pressure alarm", "unit": "unitless"},
    "6992": {"label": "Ventilation Alarm", "unit": "unitless"},
    "8023": {"label": "Respiration alarm", "unit": "unitless"},
    "9891": {"label": "Ventilation Alarm", "unit": "unitless"},
    "31060": {"label": "Respiration alarm", "unit": "unitless"},
    "32210": {"label": "Ventilation Alarm", "unit": "unitless"},
    "32220": {"label": "Ventilation Alarm", "unit": "unitless"},
    "50212": {"label": "Device Info variables", "unit": "unitless"},
    "71063": {"label": "Respiration alarm", "unit": "unitless"},
    "72111": {"label": "Respiration alarm", "unit": "unitless"},
    "72210": {"label": "Ventilation Alarm", "unit": "unitless"},
    "72220": {"label": "Ventilation Alarm", "unit": "unitless"},
    "72312": {"label": "Pressure alarm", "unit": "unitless"},
    "72313": {"label": "Pressure alarm", "unit": "unitless"},
    "1131202": {"label": "Ventilation Alarm", "unit": "unitless"},
    "1131203": {"label": "Pressure alarm", "unit": "unitless"},
    "1131204": {"label": "NIBP alarm", "unit": "unitless"},
    "1131205": {"label": "NIBP alarm", "unit": "unitless"},
    "1131206": {"label": "Ventilation Alarm", "unit": "unitless"},
    "1131207": {"label": "Ventilation Alarm", "unit": "unitless"},
    "1131208": {"label": "Pressure alarm", "unit": "unitless"},
    "92611": {"label": "Ventilation Alarm", "unit": "unitless"},
    "92612": {"label": "Ventilation Alarm", "unit": "unitless"},
    "1131101": {"label": "Device Info variables", "unit": "unitless"},
    "1131104": {"label": "Device Info variables", "unit": "unitless"},
    "52515": {"label": "CO2 variable", "unit": "unitless"},
    "52517": {"label": "CO2 variable", "unit": "unitless"},
    "1398": {"label": "Ventilation variable", "unit": "unitless"},
    "6986": {"label": "SBT variable", "unit": "unitless"},
    "9123": {"label": "SBT variable", "unit": "unitless"},
    "9145": {"label": "Respiration variable", "unit": "unitless"},
    "52211": {"label": "Ventilation variable", "unit": "unitless"},
    "52323": {"label": "Ventilation variable", "unit": "unitless"},
    "54072": {"label": "Ventilation variable", "unit": "unitless"},
    "1131102": {"label": "Ventilation variable", "unit": "unitless"},
    "1131103": {"label": "Ventilation variable", "unit": "unitless"},
    "5359": {"label": "Ventilation variable", "unit": "unitless"},
    "3668": {"label": "Pressure variable", "unit": "unitless"},
    "7498": {"label": "Pressure variable", "unit": "unitless"},
    "7519": {"label": "Pressure variable", "unit": "unitless"},
    "9288": {"label": "Ventilation variable", "unit": "unitless"},
    "52254": {"label": "Airway variable", "unit": "unitless"},
    "52341": {"label": "Pressure variable", "unit": "unitless"},
# ...existing code...
    "8581": {"label": "PEEP Not Achieved Alarm", "unit": "unitless"},
    "2046": {"label": "Flow Sensor Alarm", "unit": "unitless"},
    "5712": {"label": "Low EtCO2 Alarm", "unit": "unitless"},
    "5713": {"label": "High EtCO2 Alarm", "unit": "unitless"},
    "826": {"label": "Device Internal Temperature Alarm", "unit": "unitless"},
    "810": {"label": "Inspiratory Sensor Disconnected Alarm", "unit": "unitless"},
    "811": {"label": "Expiratory Sensor Disconnected Alarm", "unit": "unitless"},
    "8301": {"label": "Nebulizer Error", "unit": "unitless"},
    "812": {"label": "Fresh Gas Alarm", "unit": "unitless"},
    "8601": {"label": "High FiCO2 Alarm", "unit": "unitless"},
    "822": {"label": "Battery Charger Failure", "unit": "unitless"},
    "8625": {"label": "High O2 Supply Pressure Alarm", "unit": "unitless"},
    "8622": {"label": "Primary Audio Failure", "unit": "unitless"},
    "8623": {"label": "Backup Audio Failure", "unit": "unitless"},
    "8626": {"label": "Air Supply Pressure Alarm", "unit": "unitless"},
    "2899": {"label": "Flow Sensor Type", "unit": "unitless"},
    "8589": {"label": "High Expired Tidal Volume Alarm", "unit": "unitless"},
    "7452": {"label": "Device Operation Mode", "unit": "unitless"},
    "8613": {"label": "Breathing System Failure Alarm", "unit": "unitless"},
    "386": {"label": "Device Calibration Status", "unit": "unitless"},
    "8627": {"label": "Backup Mode Active Status", "unit": "unitless"},
    "8631": {"label": "Vent Check Date", "unit": "unitless"},
    "2895": {"label": "Device Displayed Unit Code of CO2", "unit": "unitless"},
    "3888": {"label": "Sigh Breath Status", "unit": "unitless"},
    "50203": {"label": "Device Model", "unit": "unitless"},
}